[build]
  command = "yarn build"
  publish = "dist/client"
  functions = "dist/server"

[[redirects]]
  from = "/trend"
  to = "/.netlify/functions/trend"

[[redirects]]
  from = "/trend.json"
  to = "/.netlify/functions/trend"